- hosts: all
  vars_files:
    - vars/defaults.yml
    - vars/sampleapp.yml
  remote_user: "{{ deploy }}"
  roles:
    ### Site specific roles:
    - { role: prepare_site_sampleapp, tags: ['prepare_site_sampleapp'] }
